version: '3'
services:
  flask-app:
    image: karenwang97/as3-app:v7
    ports:
      - 5001:5000
    volumes:
      - ./data:/data
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
